### PR TITLE
Fix id collision

### PR DESCRIPTION
**Pull request by justuswilhelm**

### CODE REVIEW

**Review by paolotiu — APPROVED** [review]

**Comment by paolotiu** [comment]
Fixes #2

**Comment by paolotiu** [comment]
Thank you so much @justuswilhelm for this!

**Comment by justuswilhelm** [comment]
I really appreciate that you got back so quickly. Thank you a lot 😄

**Comment by paolotiu** [comment]
For transparency, these commits were manually removed by me due to the request of the author. I intend no hostility and wish them the best.

**Pull request merged**
